### ISSUE TITLE
Converting to documentation / book

### ISSUE THREAD

**Issue by eddiejaoude** [domnikl/DesignPatternsPHP#114]
It would be great & very useful if this could be converted to a PDF book & to gh-pages ( something like http://couscous.io )

**Comment by eddiejaoude** [comment]
Hope you had a good New Years eve!

How do I do a link without specifying the extension? eg. if I specify the extension `rst` & generate html, then it won't work, if I specify the extension `html` it works but I feel that is wrong?

**Comment by aik099** [comment]
> How do I do a link without specifying the extension? eg. if I specify the extension rst & generate html, then it won't work, if I specify the extension html it works but I feel that is wrong?

By default if you create an internal link, then it is assumed to be in RST format and extension isn't required.
Here is how to create external links: http://docutils.sourceforge.net/docs/user/rst/quickref.html#hyperlink-targets

Google is pretty good at searching RST documentation by the way as well.

**Comment by eddiejaoude** [comment]
> Google is pretty good at searching RST documentation by the way as well.

I wasn't being lazy, I did have a look, but with or without the `rst` extension it didn't work (only with `html` extension). 

I looked at the following docs:
http://sphinx-doc.org/rest.html#hyperlinks
http://sphinx-doc.org/markup/inline.html#ref-role

I will research more, sorry to trouble you :smile:

**Comment by eddiejaoude** [comment]
I needed to use `:doc:` instead of `:ref:`. Easy when you know how :wink:

**Comment by aik099** [comment]
I you would like to create PR with your existing progress, then I can take a look at it. It's pretty hard without actually seeing RST content you're talking about. Just add `[WIP] ` before PR title (means work in progress).

**Comment by eddiejaoude** [comment]
Sure https://github.com/domnikl/DesignPatternsPHP/pull/115

**Comment by fhferreira** [comment]
+1

**Comment by eddiejaoude** [comment]
As this is now done, I am going to close this ticket. Great work all involved :+1:
