### ISSUE TITLE
Would you please add a tutorial of how to configure phpunit environment using PHPStorm?

### ISSUE THREAD

**Issue by phoenixg** [domnikl/DesignPatternsPHP#124]

**Comment by malukenho** [comment]
@phoenixg I think It's not the best place to do this kind of question.
Anyway you can search on google or youtube,

[See documentation about it](https://www.jetbrains.com/phpstorm/help/run-debug-configuration-phpunit.html)

**Comment by phoenixg** [comment]
I've watched a youtube video but tried failed, thank you, I will see the documentation then.
