### ISSUE TITLE
Version in other languages?

### ISSUE THREAD

**Issue by leonampd** [domnikl/DesignPatternsPHP#134]
Hey! Whats'up?!

Is there some version of this repo in other language? I've forked this repo yesterday to translate to portuguese.

---
### To contribute in translation, check Translation Rule/Hint below

 [important] Before your start, re-fork this project or synchronize your repo with upstream!(because i just do some change)
## Translation Rule/Hint
1. All po files were generated by all README.rst, Only them (explication of patterns) will be translated, Code and comments should be in English and not change. code is always the core of this repo.
2. Word for Word translation is **not** needed, you can add your own explication to make translation much easy to understand. 
3. if you didn't found the language you want to translate, take a look at [here](http://sphinx-doc.org/latest/config.html#confval-language), and @shangguokan who will add initial files.
4. You can use [po editor](http://stackoverflow.com/questions/393267/what-good-alternatives-to-poedit-are-there) or text editor to translate.
5. It remain some markup in po files, please be careful not to break [reST notation](http://docutils.sourceforge.net/docs/user/rst/quickref.html).

**example**: [Russian translation is completed](https://github.com/domnikl/DesignPatternsPHP/tree/master/locale/ru/LC_MESSAGES)

```
#: ../../Creational/AbstractFactory/README.rst:22
msgid "You can also find these code on `GitHub`_"
msgstr "在 `GitHub`_ 上查看代码"   (`xxx`_ one underscore here)

#: ../../Creational/AbstractFactory/README.rst:24
msgid "AbstractFactory.php"
msgstr ""                         (do not need translate xxx.php, keep it empty)
```
### PR

if you finished, make one pull request or by "Russian translation part one two..."(maxi five)
i will create project on read the doc and translation will be hosted at http://designpatternsphp.readthedocs.org/{language_slug}/latest/
### Language

| language(click to preview) | translator |
| --- | :-: |
| ca – Catalan | @torrentalle |
| en – English | @domnikl |
| [es – Spanish](http://designpatternsphp-es.readthedocs.org/es/latest/README.html) | @torrentalle   @desarrolla2 |
| [pt_BR – Brazilian Portuguese](http://designpatternsphp-pt-br.readthedocs.org/pt_BR/latest/) | @leleonam   @bgsouza  @davispeixoto |
| [ru – Russian](http://designpatternsphp-ru.readthedocs.org/ru/latest/) | @KIVagant |
| [zh_CN – Simplified Chinese](http://designpatternsphp-zh-cn.readthedocs.org/zh_CN/latest/) | @su-xiaolin     @yplam |
### Title

It's **possible** to change english wikipedia link of title to the localized version.
three formats are possible:

```
//take care of the num of underscore

#: ../../Behavioral/ChainOfResponsibilities/README.rst:2
msgid "`Chain Of Responsibilities`__"

//1. only keep russian title, russian link on russian title
msgstr "`Цепочка обязанностей <https://ru.wikipedia.org/wiki/Цепочка_обязанностей>`_" 

or
//2. keep two version titles, russian link on russian title, english link on english title
msgstr "`Цепочка обязанностей <https://ru.wikipedia.org/wiki/Цепочка_обязанностей>`_ (`Chain Of Responsibilities`__)"

or
//3. keep two version titles, russian link on russian title, no english link
msgstr "`Цепочка обязанностей <https://ru.wikipedia.org/wiki/Цепочка_обязанностей>`_ (Chain Of Responsibilities)"

or
//4. if no russian wikipedia page,so english link on russian title
msgstr "`Цепочка обязанностей`__" 

// I think 1 and 3 are best way
```
### FAQ
1. How can i add some link or bold on the translation string?
   you can use reST markup.
   `msgstr "External **hyperlinks**, like `Python <http://www.python.org/>`_."`
2. How can i test my translation?
   first, you **don't need** test your translations. if you want,
   the repo use Sphinx + reStructuredText
   a.install sphinx on your computer http://sphinx-doc.org/
   b.learn how translation works http://sphinx-doc.org/latest/intl.html
   c.Install sphinx-intl by pip install sphinx-intl or easy_install sphinx-intl.
   d.execute $ sphinx-intl build
   e.execute $ make -e SPHINXOPTS="-D language='pt_BR'" html
   f.you can find html in folder _build

**Comment by domnikl** [comment]
Currently there is only english, but it's a great idea to do this! When you are ready we could put a link to your repo in the README. What do you think of keeping all versions in branches in this repository? 

I can contribute a german translation to it. Maybe we get some other languages, too?

**Comment by leleonam** [comment]
@domnikl, 

Awesome! I'll start today, then! My repo is in https://github.com/leleonam/DesignPatternsPHP.

So, I'll start on branch 'portuguese', maybe 'spanish' too.

**Comment by nueckman** [comment]
@domnikl Translations would be awesome. Just my two cents, but if you want to use gh-pages in the future (which could be a nice addition), branches might be not the best way to deal with translations.
Why not just use subfolders ?

Another thing: 
IMO code (and comments) should always be in english. There's nothing more horrible than code like this:

```
abstract class AbstrakteFabrik
{
    /**
     * Erstellt eine Text-Komponente
     *
     * @param string $inhalt
     *
     * @return Text
     */
    abstract public function erstelleText($inhalt);
    /**
     * Erstellt eine Bild-Komponente
     *
     * @param string $pfad
     * @param string $name
     *
     * @return Bild
     */
    abstract public function erstelleBild($pfad, $name = '');
}
```

Well, mutations like "class Brücke {}" can be awesome too ;)

**Comment by davispeixoto** [comment]
How are the [PHP The Right Way](http://www.phptherightway.com/) folks doing?

I really liked the translations idea (I can even help with brazilian portuguese translation too as I'm a native speaker), but I also think we would follow some pattern that is working for another great projects and initiatives.

Empower the community is always a great thing.

**Comment by nueckman** [comment]
The translations on PHP The Right Way are forked repositories. It's possible, but spreading the code/documentation across multiple repositories/forks is kind of annoying.

**Comment by davispeixoto** [comment]
Yeap, just took a look into it.
They do forking and create a gh-page in each fork/translation, them they are linked back from the main project.

Not sure if this is really the better approach. It would be awesome (IMHO) if :
- We keep the credits to people who make the translations (accept only pull requests?)
- It is centralized repo with branches
- The distribution site (currently [readthedocs](readthedocs.org)) accept and make easy to distribute the content appropriately, like **http://designpatternsphp.readthedocs.org/en/latest/**, **http://designpatternsphp.readthedocs.org/pt-br/latest/**, **http://designpatternsphp.readthedocs.org/de/latest/**, 
**http://designpatternsphp.readthedocs.org/es/latest/**,
**http://designpatternsphp.readthedocs.org/en-gb/latest/**, etc... OR
**http://de.designpatternsphp.readthedocs.org/latest/**,
**http://pt-br.designpatternsphp.readthedocs.org/latest/**, etc...

What you guys think?

**Comment by leleonam** [comment]
Hey everybody,

I'm contributing to https://github.com/vhf/free-programming-books. Here we have a list of markdowns which is a translation from english.

**Comment by domnikl** [comment]
I am with @davispeixoto, it should be all in a centralized repository, that makes fixing translations and in general contributing to them much easier IMO. And of course PR are a good thing too. I don't know if we should use branches or subfolders and I think this depends on readthedocs.org (I don't think we should use gh-pages as this would be another platform we have to support). 

@shangguokan what do you think about branches vs. subfolders in regards to read the docs?

And I am with @nueckman, Code should be in english and comments too!

**Comment by shangguokan** [comment]
@domnikl i will try to add another language on read the docs, and tell your the results after.

**Comment by leleonam** [comment]
I found this https://docs.readthedocs.org/en/latest/localization.html#localization-of-documentation on the RTD website. I think we'll need a repo for each translation. Am I right?

**Comment by domnikl** [comment]
I found this https://github.com/rtfd/readthedocs.org/issues/4, so we can use branches for the translations. There needs to be a project on RTD for every translations but multiple projects for the same repositories are possible and the branch can be configured in the advanced settings of a project.

**Comment by leleonam** [comment]
Use branches for translations, sounds good, to me. And you guys?

**Comment by shangguokan** [comment]
Two ways:
First, for every translation (fr, zh...), we need to fork and create one repo of github and one project of RTD (designpatternsphp, designpatternsphp-fr, designpatternsphp-zh...), and create connection on these projects.

Second, sphinx doc can load .po/.mo translation files to finish translation job, so we don't need to create any branch of translation or repo of translation, just add translation files in the main repo, and sphinx can load these files, but i'm not sure RTD support this feature, so i open one issues here: https://github.com/rtfd/readthedocs.org/issues/1280

I’m waiting the response, but if the second way is not possible, we use branch.

and before that i have to do some changes for every .rst and conf.py, because for no-english, there have some problem on PDF generated.

**Comment by torrentalle** [comment]
I can start with spanish and catalan translations, my natural languages

**Comment by domnikl** [comment]
@torrentalle :+1:

**Comment by leleonam** [comment]
So, how we'll working on translations? We'll use branches or repos for each translation?

:)

**Comment by shangguokan** [comment]
sorry i was a litte busy, we don't need any repo and any branch to do translation, i will create po translation files on the main repo main branch. whitch language? portuguese? you can find directory named _locale/pt_BR or _locale/pt_PT
pt_BR – Brazilian Portuguese
pt_PT – European Portuguese
which one?

**Comment by leleonam** [comment]
@shangguokan, no problems! I can help to translate for Brazilian Portuguese. Spanish, maybe. :)

**Comment by bgsouza** [comment]
Hi @shangguokan 

I am a friend of @leleonam.
I'm ready to help! :-)

**Comment by shangguokan** [comment]
I have already add po translations files, you can find them in [locale](https://github.com/domnikl/DesignPatternsPHP/tree/master/locale)
ca – Catalan
es – Spanish
pt_BR – Brazilian Portuguese

you can take poedit or any other text editor to add your translation string, and make a PR!

**Comment by KIVagant** [comment]
Hello.

Please, add folders for the Russian language. I can help to translate.

**Comment by shangguokan** [comment]
Hi, thank you~, it is added in the locale folder
ru – Russian

**Comment by KIVagant** [comment]
Thank you.  I'll do it when I will take a break from the my project.

**Comment by davispeixoto** [comment]
Just for cultural information, Portuguese currently is the [sixth most spoken language](http://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers#Nationalencyklopedin), with 215 million people as first language, and 262 million as first or second language.

Brazil has 200 million people, thus pt-br is the way to go with translations for portuguese.

**Comment by su-xiaolin** [comment]
@shangguokan 
Hello.

Please, add folders for the zh_CN language. I can help to translate.

**Comment by torrentalle** [comment]
It's possible to add the localized wikipedia links in po files?

**Comment by leleonam** [comment]
Guys,

I have to say that I'm proud. It's good to know that you liked the idea. Let's share knowledge! thank u guys! :)

**Comment by shangguokan** [comment]
[important] Before your start, re-fork this project or synchronize your repo with upstream!
### Translation Rule/Hint
1. All po files were generated by all README.rst, Only them (explication of patterns) will be translated, Code and comments should be in english and not change.
2. Word for Word translation is not needed, you can add your own explication to make translation much easy to understand. 
3. [Supported languages](https://github.com/domnikl/DesignPatternsPHP/tree/master/locale), if you didn't found the language you want to translate, take a look at [here](http://sphinx-doc.org/latest/config.html#confval-language), and tell me. i will add initial files.
4. You can use [po editor](http://stackoverflow.com/questions/393267/what-good-alternatives-to-poedit-are-there) or text editor to translate.
5. It remain some markup in po files, please be careful not to break [reST notation](http://docutils.sourceforge.net/docs/user/rst/quickref.html).

example: [Creational/AbstractFactory/README.po](https://github.com/domnikl/DesignPatternsPHP/tree/master/locale/zh_CN/LC_MESSAGES/Creational/AbstractFactory)
```
#: ../../Creational/AbstractFactory/README.rst:2
msgid "`Abstract Factory`__"
msgstr "`抽象工厂`__"                (`xxx`__ two underscore here)


#: ../../Creational/AbstractFactory/README.rst:22
msgid "You can also find these code on `GitHub`_"
msgstr "在 `GitHub`_ 上查看代码"   (`xxx`_ one underscore here)

#: ../../Creational/AbstractFactory/README.rst:24
msgid "AbstractFactory.php"
msgstr ""                         (do noot need translate xxx.php, keep it vide)
```
6.if you finished, make a pull request and i will create projet on read the doc and translaton will be hosted at http://designpatternsphp.readthedocs.org/{language_slug}/latest/
### Language

| language                                | translator           | 
| ------------------------------------- |:-------------:| 
| ca – Catalan                           | @torrentalle  |
| en – English                           | @domnikl  |
| es – Spanish                           | @torrentalle       |
| pt_BR – Brazilian Portuguese | @leleonam   @bgsouza  @davispeixoto    | 
| ru – Russian                           | @KIVagant      | 
| zh_CN – Simplified Chinese   | @su-xiaolin       | 

### FAQ
1.It's possible to add the localized wikipedia links in po files?
@torrentalle It's not possible to add the localized wikipedia links in po files, **all titles** is linked to english version. as in wikipedia, we can choose language. if you want to add some link in your translation string, you can use reST markup.
```
External hyperlinks, like `Python <http://www.python.org/>`_.
```

**Comment by KIVagant** [comment]
> all titles is linked to english version. as in wikipedia, we can choose language

Does it mean, than we should not change titles or we can change title to something like that?:

```
`Chain Of Responsibilities <http://{locale}.wikipedia.org/link-to-this-article>`__
```

**Comment by shangguokan** [comment]
no, just translate all titles to russian, do not add any other things on the title, il will break the index of generated pdf.

#: ../../Behavioral/ChainOfResponsibilities/README.rst:2
msgid "`Chain Of Responsibilities`__"
msgstr "`Цепочка обязанностей`__"

it means only text is changed to Цепочка обязанностей, but link is always on english version wikipedia. we can choose russian in wikipedia page.

**Comment by KIVagant** [comment]
What you plan to do, when some english phrases will changed? Replace it msgid inside all translations?

**Comment by shangguokan** [comment]
if it is just a small change, it's unnecessary to update all translations. the object of READMEs and translations are explain patterns.
if we add a big and important part in english README, there is a command to automatic update all translations by replace or add msgid in po files

**Comment by KIVagant** [comment]
I have to go back to the question about translating of titles. I need a way to present the localization of both versions: the English and the local. Because many programmers know the name of the template in the original version. Translations can be very different in different sources, which causes confusion.
It is necessary, that contents of the documentation should not be corrupted. For example, original English titles can be shown under local title on each page.

Like this:
[**Цепочка Обязанностей**](/)
[(*Chain Of Responsibilities*)](/)

**Comment by shangguokan** [comment]
```
#: ../../Behavioral/ChainOfResponsibilities/README.rst:2
msgid "`Chain Of Responsibilities`__"
msgstr "`Цепочка обязанностей`__ (Chain Of Responsibilities)"

or

msgstr "Цепочка обязанностей (`Chain Of Responsibilities`__)"
```

**Comment by KIVagant** [comment]
Unfortunatelly, by this way will broke TOC.
Can we add new line after title?
```
msgstr "`Цепочка обязанностей`__\n(Chain Of Responsibilities)"
```

**Comment by shangguokan** [comment]
i'm sure this will not break TOC tree, i have test
u can use this
```
#: ../../Behavioral/ChainOfResponsibilities/README.rst:2
msgid "`Chain Of Responsibilities`__"
msgstr "`Цепочка обязанностей`__ (Chain Of Responsibilities)"

or

msgstr "Цепочка обязанностей (`Chain Of Responsibilities`__)"
```

**Comment by KIVagant** [comment]
Ok, if it's looks nice, then I will use this form.

**Comment by shangguokan** [comment]
@torrentalle @KIVagant 
Sorry about what i said on the title, it's ok to add link on the title. please check the "Translation Rule/Hint" section "title".

**Comment by KIVagant** [comment]
Ru: finished (except Memento, in separate PR)

**Comment by KIVagant** [comment]
Suggestion: [add links](http://designpatternsphp.readthedocs.org/en/latest/) to all available languages in header. Ideally, each page should have link to the appropriate page in other languages.

**Comment by shangguokan** [comment]
i think now it's 02:12 in Russia

**Comment by leleonam** [comment]
Hey guys, I'm so sorry. I couldn't translate anything yet because I'm very busy but I promiss that we'll have a PR for portuguese next weekend

**Comment by shangguokan** [comment]
it's ok :smile: i'm also very busy

**Comment by KIVagant** [comment]
@leleonam, there is no deadline

**Comment by shangguokan** [comment]
UPDATE [2015/06/01 -> 2016/06/03](https://github.com/domnikl/DesignPatternsPHP/compare/master@%7B2015-06-01%7D...master)
[Commit](https://github.com/domnikl/DesignPatternsPHP/commit/557ac019b13d61a6641266c8928d75f8c8b2fc9a)
Here is the todo list, these patterns need to be **translated** or **retranslated**, check relevant .po files

- Behavioral/Memento/README.rst

- More/Delegation/README.rst

- More/EAV/README.rst

- Structural/Flyweight/README.rst

**Comment by domnikl** [comment]
Is someone working on the missing translations for ES? Unfortunately I do not speak spanish. Would love to merge a PR for it so we can close this issue. Thank you all for the already translated languages!

**Comment by axelitus** [comment]
I did start yesterday doing a translation for es_MX. I did however decided to start doing a POT template first so that new translations would be easy to begin. It's going somewhat slow because right now at work we are doing budgets for next year so you know how that goes...

Also I think translations should be versioned with the commit they are working with. Any thoughts about this? This way it's easier to track which translations aren't up to date with changes made to the repo.

**Comment by axelitus** [comment]
I've just finished the templates for Behavioral patterns. Take a look [here](https://github.com/axelitus/DesignPatternsPHP/tree/translate-template/locale/template/LC_MESSAGES).

I did some small changes (punctuation mostly) on the RST files which may break already existing translations. But anyway I think the translation should be updated to the PO templates once they are finished anyways for the sake of future updates.

Once I finish with the PO templates I'll do the es_MX translation.

**Comment by axelitus** [comment]
I have translated already all Behavioral and Creational patterns to es_MX.

Currently I don't have a way of testing the translation. I think I'll finish the translation tomorrow or saturday at latest.

**Comment by axelitus** [comment]
I have looked into this and I think Read the Docs doesn't allow for specific language *forms*, like es_MX. There are only a few of them in their system, like Brazilian Portuguese (pt_BR) or Simplified Chines (zh_CN).

There can only be one Spanish translation as far as I know, which will be directed to "/es/<docs>". Selection boxes are a nice way to simplify things, but they can introduce limitations like this 😛.

**Comment by shangguokan** [comment]
This is supported languages list:
http://www.sphinx-doc.org/en/stable/config.html#confval-language

**Comment by yaim** [comment]
Dear @shangguokan, please add files for the fa_IR language. I can help to translate.

**Comment by piotrgradzinski** [comment]
Hi guys! 
I can help with the polish translation, so can you create files for pl language? If there is other way how this can be done please give me note. Thanks!

**Comment by domnikl** [comment]
Closing this as there are already some translations. Thank you! If anyone needs help adding new languages, contact me.
