### ISSUE TITLE
Could we add entity-attribute-value (EAV) pattern?

### ISSUE THREAD

**Issue by bocharsky-bw** [domnikl/DesignPatternsPHP#155]
Does [EAV](https://en.wikipedia.org/wiki/Entity%E2%80%93attribute%E2%80%93value_model) pattern suitable for this repo? What do you think, guys?

**Comment by dupuchba** [comment]
Great idea IMO :-). Who does have time to do it ?

**Comment by bocharsky-bw** [comment]
I could have a time if most think this is a good idea

**Comment by dupuchba** [comment]
:+1:

**Comment by andrewnester** [comment]
I guess this one could be closed, right? @domnikl

**Comment by bocharsky-bw** [comment]
Indeed, thanks @andrewnester !
