### ISSUE TITLE
Updating examples to use PHP7 strict mode?

### ISSUE THREAD

**Issue by eddiejaoude** [domnikl/DesignPatternsPHP#167]
Types become really important here and interesting.

PR: https://github.com/domnikl/DesignPatternsPHP/pull/169
Fork: https://github.com/eddiejaoude/DesignPatternsPHP

**Comment by axelitus** [comment]
I think the question here should be: ¿should the code be upgraded to PHP7 and drop support for older versions?

I definetely vote for it, though not everybody is using PHP7 yet. I think the new features introduce in PHP7 should be harness.

**Comment by a-komarev** [comment]
Maybe it will be good to have support branch with old PHP version then?

**Comment by domnikl** [comment]
I know you would all love to see PHP7 features in here. I do so myself. Support for 5.6 will last till the end of the year (http://php.net/supported-versions.php) so I think we should just start and have it ready in early 2017. @eddiejaoude are you still working on the mentioned PR? It seems to have conflicts and can't be merged. If not I would start working on PHP7 feature use and merge if it is ready.

@a-komarev I don't think a support branch will be necessary. Anyone not familiar with PHP7 features could easily go back to the current state (maybe set a tag for it and link in the README). It's just educational after all, no support for older versions needed.

**Comment by eddiejaoude** [comment]
I have not looked at this in a while as it didn't have any comments for over a year. I am sure the fork I did mid last year is out of date by now.

**Comment by domnikl** [comment]
@eddiejaoude sorry to let you wait for so long. I'll have a look into it, thanks!

**Comment by domnikl** [comment]
Merged it just now. If I missed anything, please let me know in a new issue or PR, thanks!
