### ISSUE TITLE
Use styleCI to automate your php linting process

### ISSUE THREAD

**Issue by jadjoubran** [domnikl/DesignPatternsPHP#171]
This is just a suggestion, but I'd recommend you use https://github.com/StyleCI/StyleCI/
to automate your php linting process that is described in your readme.md

It's free for open source, and you'll get the github health API integration ;)

This is an example:
https://github.com/jadjoubran/laravel5-angular-material-starter/pull/23

**Comment by andrewnester** [comment]
I guess this one is already used for this repository, am I right @domnikl ?

**Comment by domnikl** [comment]
@andrewnester right, I added it just recently, closing this.
