### ISSUE TITLE
Adding examples

### ISSUE THREAD

**Issue by ghost** [domnikl/DesignPatternsPHP#175]
Even if most patterns are self-explaining we should provide usage examples. Any thoughts?

**Comment by xiangweilee** [comment]
Perhaps you can see usage examples inside test folder?

**Comment by domnikl** [comment]
Yes, the tests are the usage examples. If the tests are not clear enough, we should fix it and not provide other examples.

**Comment by nueckman** [comment]
IMO tests can't be examples per definition. Especially not unit tests which are build to verify the functionality of most atomic units. But i think it depends on the purpose of this repository. Do you want to show PHP devs how to use a known pattern in PHP or do you want to explain the usage of patterns too.

**Comment by thehamsterofgod** [comment]
:+1: 

I agree with @nueckman, and probably code that shows the simplest but best real world usage scenario, it would really be helpful for beginners. Thank you for this repo it really helped me alot. :smile: 7

>I think the problem with patterns is that often people do know them but don't know when to apply which.

**Comment by ganesh-patil** [comment]
Hi All,
'I am interested to work on design patterns. shall  I start adding examples of design patterns?can you please explain which directory structure we are going to follow ?

Thanks.

**Comment by doidd** [comment]
### You can see simple my example (require install composer): 
__Step 1:__ Create file index.php in root folder (my example __dpp__)
__Step 2:__ Wire content with code below
```php
<?php
//show error when debug
error_reporting(E_ALL);
ini_set('display_errors', TRUE);
ini_set('display_startup_errors', TRUE);

//insert autoload.
require 'vendor/autoload.php';


// Example use Design Patterns Dependency Injection
use DesignPatterns\Structural\DependencyInjection\ArrayConfig;
use DesignPatterns\Structural\DependencyInjection\Connection;

//Code in file t
$config = array('host' => 'github.com');
$setup = new ArrayConfig($config);
$connection = new Connection($setup);
$connection->connect();
echo $connection->getHost();
```
__Step 3:__ go to browser enter url host (__localhost/dpp__)  and see that

**Comment by ganesh-patil** [comment]
Thanks,

Will follow above structure and will add examples of another design patterns.

Thanks

**Comment by domnikl** [comment]
:-1: 

Please don't do that. Here's why:

```php
//show error when debug
error_reporting(E_ALL);
ini_set('display_errors', TRUE);
ini_set('display_startup_errors', TRUE);
```

This is bad practice. PHP Settings should not be in example code! 

```php
//Code in file test
$config = array('host' => 'github.com');
$setup = new ArrayConfig($config);
$connection = new Connection($setup);
$connection->connect();
```

This is exactly what happens in the unit test here: https://github.com/domnikl/DesignPatternsPHP/blob/master/Structural/DependencyInjection/Tests/DependencyInjectionTest.php#L21

Adding example code leads to exactly the usage of this repository that I want to prevent. Users coming here, copy&pasting design patterns and not think about it. 
And that is not what that is all about. This repository is just a bunch of examples put together to help understanding them and that requires a basic understanding of PHP and I don't think it's too much to read a little code and invest some time before using a certain pattern.

After all adding these examples is duplication of source code and we all know that sooner or later examples and source code will drift apart.

@jimmerioles what are real world examples? Usages differ for every implementation of a pattern, it's only examples after all. And implementing these without reading the source is no good idea.

**Comment by ganesh-patil** [comment]
Ok, Thanks.

**Comment by 20uf** [comment]
+1

**Comment by axelitus** [comment]
I agree with @domnikl, the documentation (explanation text) + pattern application (code + UML diagram) and tests should be enough to explain how the pattern works (if it's not then something must be changed in order to fulfill this).

The repo should not have every example of every implementation known to man, because real world usage scenarios are _infinte_. The purpose should not be to solve a specific application requirement (thus the examples should be as uncluttered as possible) but to serve as a starting point for everybody to apply to their own code as they see fit.

**Comment by domnikl** [comment]
I will close this now, I think we got a consesus here and @axelitus has just summed it up perfectly!
