### ISSUE TITLE
VehicleInterface don't found anywhere in the builder pattern

### ISSUE THREAD

**Issue by pjurasek** [domnikl/DesignPatternsPHP#181]
In the builder pattern in Vehicle.php I found line: 
"VehicleInterface is a contract for a vehicle" - but don't see any Vehicle Interface anywhere. So the code is missing? what is wrong with this code? Thanks.
I feel a bit confused about it.

**Comment by andrewnester** [comment]
Hi @pjurasek 
You are right, there is no VehicleInterface, only Vehicle abstract class
I've made PR to fix this
