### ISSUE TITLE
phpunit There was 1 error: Argument 1 passed to AbstractFactoryTest::testComponentCreation() must be an instance of AbstractFactory, none given

### ISSUE THREAD

**Issue by wozzup** [domnikl/DesignPatternsPHP#186]
hey, guys, please take a look, what happened this error:

```
wozzup@u1404:~/php/Creational/AbstractFactory$ phpunit Tests/AbstractFactoryTest.php
PHPUnit 3.7.28 by Sebastian Bergmann.

E

Time: 49 ms, Memory: 2.50Mb

There was 1 error:

1) Creational\AbstractFactory\Tests\AbstractFactoryTest::testComponentCreation
Argument 1 passed to Creational\AbstractFactory\Tests\AbstractFactoryTest::testComponentCreation() must be an instance of Creational\AbstractFactory\AbstractFactory, none given

/home/wozzup/php/Creational/AbstractFactory/Tests/AbstractFactoryTest.php:19

FAILURES!
Tests: 1, Assertions: 0, Errors: 1.
```

do i need to composer autoload `"squizlabs/php_codesniffer": "1.5.*"` to get phpunit work?

**Comment by domnikl** [comment]
Hi @wozzup,

CodeSniffer has nothing to do with phpunit and is not required to run the tests. Please provide some more information so we can help you:

* which version of DesignPatternsPHP are you testing against?
* maybe you could post the complete contents of `Creational\AbstractFactory\Tests\AbstractFactoryTest`

Also the current version of PHPUnit is 5.0 and you should always use the latest version of it when possible (that reminds that composer.json needs an update too).

**Comment by wozzup** [comment]
awesome! fixed
