### ISSUE TITLE
design patterns for real projects

### ISSUE THREAD

**Issue by tonicospinelli** [domnikl/DesignPatternsPHP#190]
hey dudes, some days ago I was reading codes from this repo I have an idea. Would be nice to have some libraries with abstract implementation of Design Patterns so I can use in real project!

What it means?
Something like PSRs and we could create a organization with some repositories to provide the way to implement one specific pattern 

Look like, create a abstract structure to someone implement a Chain of Responsibility? You know...

**Comment by HassanAlthaf** [comment]
The purpose of this repository is to teach users how to implement generally used design patterns in real world scenarios. These are in general, and not language specific. Neither are they anyones creation. Therefore, an organisation is not necessary to be setup to enforce this. It is not necessary to enforce these, as they are already practiced.

**Comment by domnikl** [comment]
@HassanAlthaf +1

**Comment by 20uf** [comment]
@HassanAlthaf +1

**Comment by HassanAlthaf** [comment]
@domnikl I suggest closing this issue.
