### ISSUE TITLE
Create a coding standard for this documentation

### ISSUE THREAD

**Issue by marius-rizac** [domnikl/DesignPatternsPHP#193]
This is a very good repository to explain Design Patterns in PHP but I think it would be better to have a coding standard for it.

Some examples:
> Do not add non sens comments in docblocks like:
```php
/**
 * Class MyClass  // this comment should not be here
 */
class MyClass
{
    // ...
}
```
> Docblock for constants in classes should not contain `@var`. They are constants, not variables.

Is not necessary to add `@abstract` in docblock for a method declared abstract. It can be seen from method's declaration itself.
```php
/**
 * @abstract // this should not be here.
 * @var int $idSomething
 */
abstract public function doSomething($idSomething);
```

> Do not add empty docblock for classes or methods like in this class https://github.com/domnikl/DesignPatternsPHP/blob/master/Structural/Facade/Facade.php

The list can continue and I believe it could add a lot of improvements to the examples.

**Comment by cirpo** [comment]
what about using PSR-2 and the php-cs-fixer tool? There is even a free online service: https://styleci.io/

**Comment by spekulatius** [comment]
Agree. There are plenty of free options for code quality tool out there.

**Comment by vienmar** [comment]
I like @cirpo's suggestion [https://styleci.io/]

**Comment by domnikl** [comment]
As a quick test, I enabled styleci.io: https://styleci.io/repos/2246815
Will have a deeper look at it over the next week

**Comment by marius-rizac** [comment]
:+1:

**Comment by domnikl** [comment]
styleci is now used, so I am closing this issue.
