### ISSUE TITLE
MVC

### ISSUE THREAD

**Issue by akmorp** [domnikl/DesignPatternsPHP#209]
Not enough MVC pattern.

**Comment by mCzolko** [comment]
MVC is not a pattern but an ideology.

**Comment by akmorp** [comment]
Ok. I would like to see the implementation of this ideology in this repository.

**Comment by hgraca** [comment]
Its actually and Architectural Pattern, so its about the application structure in broader strokes, its aimed at solving higher level problems than the design patterns in this repository. 
https://basicsofwebdevelopment.files.wordpress.com/2015/01/mvc_role_diagram.png

Nevertheless, it could indeed be implemented here in a basic form.

**Comment by domnikl** [comment]
As @hgraca already said, it is an architectural pattern and is therefore not related to design patterns in this repository. I'd like to keep archtictural patterns out from here, because that would be just too much stuff. How about you start a repo for architectural patterns @akmorp?
