### ISSUE TITLE
Specification pattern issues

### ISSUE THREAD

**Issue by ihor** [domnikl/DesignPatternsPHP#215]
Hey guys,

What do you think about changing ```Specification``` pattern example? At the moment it has the following issues:

1. ```Specification``` interface contains ```plus```, ```either``` and ```not ```methods which put on ```Specification``` object redundant responsibilities. Instead of checking if some certain condition is satisfied it is also responsible for creating new specifications. This is not a good approach and may create wrong impression on people who are not familiar with the pattern.

2. ```AbstractSpecification``` class knows about its children. While sometimes it adds some convenience, in general, it is a bad design.

3. ```Plus``` and ```Either``` specifications have an arity of two while they can operate on any number of specifications (in case we want to show them in the example).

4. Plus refers to the mathematical operation of addition while specifications return boolean results and I would stick with the standard boolean logic operations. I suspect ```Plus``` and ```Either ```names were used because ```and``` and ```or``` are reserved words but we can call them ```AndSpecification```, ```OrSpecification```, and ```NotSpecification```. These names look worse if we want our code to look more like a natural language but in this case, in my opinion, they increase readability. Because the name ```AndSpecification``` less likely will confuse somebody.

I propose to:

1. Remove ```plus```, ```either``` and ```not``` methods from the ```Specification``` interface
2. Remove ```AbstractSpecification``` class (it is not needed)
2. Rename ```Plus```, ```Either``` and ```Not``` specifications to ```AndSpecification```, ```OrSpecification``` and ```NotSpecification``` correspondingly
3. Change the arity of ```AndSpecification``` and ```OrSpecification``` to any number of parameters 

I didn't create a pull request because wanted to discuss this with you guys first. But I can prepare it this weekend if you agree with proposed changes.

**Comment by domnikl** [comment]
@ihor sounds good, can you prepare a PR for it? Sorry for the late feedback!

**Comment by domnikl** [comment]
@ihor I am already working on the Specification to refactor it to use PHP7 features and cleaning it up. So I will consider your change and implement it! I will close this issue as soon as I push all the changes to the php7 branch

**Comment by domnikl** [comment]
Merged the php7 branch and your feedback has been incorporated, thanks for your contribution!
