### ISSUE TITLE
Russian documentation looks outdated

### ISSUE THREAD

**Issue by KIVagant** [domnikl/DesignPatternsPHP#218]
Hello to all.

I can help to translate some new patterns for RU locale:  ```More/EAV``` and ```Structural/Flyweight```
And, as I can imagine, EN documentation should be changed from Sep 8 2015 when I sent last PR with translation.

So, maybe some *.po files in RU locale is now outdated too. Can you check this?

UP: JFYI, [here is broken](https://github.com/domnikl/DesignPatternsPHP/tree/master/Structural/Flyweight) UML image.

**Comment by shangguokan** [comment]
HI, KIVagent
I just review all changes between [2015/06/01 - 2016/06/03](https://github.com/domnikl/DesignPatternsPHP/compare/master@%7B2015-06-01%7D...master)
And [updated](https://github.com/domnikl/DesignPatternsPHP/commit/557ac019b13d61a6641266c8928d75f8c8b2fc9a) all po files, I hope all problems have been sloved

Here is the todo list, these patterns should be translated or re-translated, check relevant .po files

- Behavioral/Memento/README.rst

- More/Delegation/README.rst

- More/EAV/README.rst

- Structural/Flyweight/README.rst

Thanks :smile_cat:

**Comment by KIVagant** [comment]
Ok, I'll try to do this later.

**Comment by NikitaStrelkov** [comment]
@shangguokan, it seems to me that after applying this #228 RP Russian documentation is up-to-date. So this issue may be closed
