### ISSUE TITLE
The UML image for 2.9 Flyweight is gone away.

### ISSUE THREAD

**Issue by godtail** [domnikl/DesignPatternsPHP#227]
![2016-08-31 10 51 42](https://cloud.githubusercontent.com/assets/18417644/18114332/ef599480-6f68-11e6-9fc8-934fe66bcc1c.png)

**Comment by NikitaStrelkov** [comment]
Add diagrams and create PR #229

**Comment by domnikl** [comment]
fixed in PR #229, thanks @NikitaStrelkov!
