### ISSUE TITLE
Composite pattern, why use abstract FormElement?

### ISSUE THREAD

**Issue by Ganganation** [domnikl/DesignPatternsPHP#234]
Hi domnikl,

Awesome examples! Learning a lot, thanks.
I have a question, why does your composite pattern uses an abstract class in stead of an interface or trait? 

Trait example:
```php
trait RenderableTrait
{
   /**
     * renders the elements' code.
     *
     * @param int $indent
     *
     * @return mixed
     */
    abstract public function render($indent = 0);
}
```

Interface example
```php
interface RenderableInterface
{
   /**
     * renders the elements' code.
     *
     * @param int $indent
     *
     * @return mixed
     */
    public function render($indent = 0);
}
```

Than you can decouple the From class from the FormElement and add the RenderableTrait or RederableInterface to the Form and FormElement class.

Forgive my possible ignorance, I'm still learning and trying to understand the why of programming decisions.

**Comment by domnikl** [comment]
Hi @Ganganation great to hear you like it! You are right, an abstract class is not necessary here and I will change it to an interface. In my experience, many not-so experienced developers are having trouble with Traits and it is also not necessary here as it does not add any functionality, therefor an interface is better suited here. I will change it in the php7 branch and notify you here once it's done.

**Comment by domnikl** [comment]
Implemented it in: https://github.com/domnikl/DesignPatternsPHP/blob/master/Structural/Composite/RenderableInterface.php

**Comment by Ganganation** [comment]
@domnikl Awesome! Thanks for your explanation. I don't really understand why not-so experienced developers are having trouble with Traits, but that's a different discussion.

The UML diagram stays the same? Or will you change that in the future as well?

**Comment by domnikl** [comment]
Oh forgot to change the UML, fixed now!

**Comment by axelitus** [comment]
Just to add my two cents here. I agree with @domnikl about the Trait not being useful here and an interface is better suited to that from a *best practices principles* (I didn't know how else to put it 😛) point of view.

Form PHP reference:

> Traits are a mechanism for code reuse in single inheritance languages such as PHP. A Trait is intended to reduce some limitations of single inheritance by enabling a developer to reuse sets of methods freely in several independent classes living in different class hierarchies.

In this example there's really no implementation, therefore IMO a trait doesn't serve any real purpose. Also an interface establishes a contract that is enforced, so we now that if a class implements an interface, then the contract is met. In a practical example this means that:

```php
public class Form implements RenderableInterface {
    /* @var FormElement[] */
    protected $elements = [];

    public function render(int $indent = 0) {
        foreach($this->element as $el) {
            $elementIndent = $indent + <relative element indentation>;
            $el->render($elementIndent);
        }
    }
}

public class FormElement implements RenderableInterface {
...
}

public class RenderEngine {
    public function run(RenderableInterface $renderableObject, int $indent = 0) {
        $renderableObject->render($indent);
    }
}

$formElements = [new FormElement(), new FormElement()];
$form = new Form($formElements);
$renderEngine = new RenderEngine();
$renderEngine->run($form); // at this point we now that Form has a render method so our run method works like a charm
```

I don't think that traits give information about contracts, so this wouldn't work (which is bad):

```php
public class RenderEngine {
    public function run(RenderableTrait $renderableObject, int $indent = 0) {
        $renderableObject->render($indent);
    }
}
```

So our code must be change to:

```php
public class RenderEngine {
    // No type inference... bad!
    public function run($renderableObject, $indent = 0) {
        // We need to check if render is even an object method
        if(method_exists($renderableObject, "render")) {
            // Method exists, yeah! But wait... is it implemented in the same way as we expect?
            // Hmmm let's hope so...
            $renderableObject->render($indent);
        } else {
            throw new InvalidArgumentException('Object does not have a render method.');
        }
    }
}
```

Certainly there are useful uses for traits, just not establishing contracts. That's what Interfaces are for.
If there was a common implementation for the render method of Form and FormElement, then a Trait with an Interface implementation would be well suited for it (a combination of both, not one or the other).

I could be wrong about traits but I'm fairly certain of it. About why Traits are cumbersome for non-experienced developers I don't have a clue.

**Comment by Ganganation** [comment]
That's one awesome explanation @axelitus, thanks! If I understand correctly. In this case the RenderableTrait would only be interesting if it would have the same render method implementation throughout all the form elements. That would never work in this example and if I understand correctly for the Composite Pattern.

Thanks again!

**Comment by axelitus** [comment]
Yes, say for example you have a BookCollection and a MovieCollection and you want both classes to have some common implementation, then you could do it like so:

```php
interface ReversableCollection {
    public function reverse();
}

trait ReversableTrait {
    public function reverse() {
        return array_reverse($this->items);
    }
}

class BookCollection {
    /* Book[] */
    $items = [];

    use ReversableTrait;
}

class MovieCollection {
    /* Movie[] */
    $items = [];

    use ReversableTrait;
}
```

This way both collection share the implementation of the reverse function through the trait, and any changes in the trait's implementation would be automatically available for both collections.

The benefit is that you don't need to duplicate code, but instead you can re-use it and maintain only one implementation (instead of two that are equal). That is the main purpose of traits. They are helpful because PHP has a single inheritance model, and sometimes you need to have implementations from different parent classes. With traits you can have something like it.

**Comment by Ganganation** [comment]
Awesome example again! This makes it very clear. Thanks.
