### ISSUE TITLE
Design pattern for version 5.6 

### ISSUE THREAD

**Issue by mishbah** [domnikl/DesignPatternsPHP#242]
I create design pattern for 5.6 https://github.com/mishbah/DesignPatternsPHP/tree/php5.6
maybe we can create another branch for 5.6

**Comment by domnikl** [comment]
Why are you doing that? PHP5.6 will only be supported till the end of the year: see http://php.net/supported-versions.php. Remember that this serves an educational purpose only!

**Comment by clytemnestra** [comment]
@domnikl It's a good idea so that people that haven't installed php7(like me) can still run them.

And php5.6 will still receieve security updates for 2 more years.

**Comment by domnikl** [comment]
@clytemnestra you can always go back in the commit history to get a version that runs on 5.6. I could add a tag for it if that would make it easier?

**Comment by clytemnestra** [comment]
There is a small problem with that as some code was added for php7 version only.

Check for instance https://github.com/domnikl/DesignPatternsPHP/commit/d151e309c5be5fde00a6120210ce7696705095e2

mishbah's version has the updated code that works for php5.6. Tests, too.

**Comment by floodedcodeboy** [comment]
Tags sound like a good idea... at the very least for completeness sake.

**Comment by domnikl** [comment]
@mishbah if you want you can send me a PR for your PHP5.6 branch and I can set a tag on it. But I am closing here now.
