### ISSUE TITLE
isn't Service Locator known as anti-pattern?

### ISSUE THREAD

**Issue by 0x13a** [domnikl/DesignPatternsPHP#251]
isn't Service Locator formerly known as anti-pattern ?
Service Locator is an Anti-Pattern since it hides class' dependencies causing issues when you change dependencies, since they are not directly exposed out of the class.

What do you think @domnikl ? :)

**Comment by domnikl** [comment]
I like it and would be happy to merge a PR marking Service Locator as an anti-pattern 👍

**Comment by domnikl** [comment]
closing here as the PR has been merged
