### ISSUE TITLE
Invalid UML diagram for Creational/Pool?

### ISSUE THREAD

**Issue by sbobrov85** [domnikl/DesignPatternsPHP#253]
It seems to me that the UML diagram for Creational/Pool a mistake because the source code is not contain Processor class and  run method for Worked does not match.
Possibly previously used different source code for example?

**Comment by rodion-arr** [comment]
Same with FactoryMethod and CarMercedes class which is not present on the diagram

**Comment by domnikl** [comment]
Updated both UML diagrams in 35f5e85 and bd3c2cf, thanks!
