### ISSUE TITLE
Final Class

### ISSUE THREAD

**Issue by undercloud** [domnikl/DesignPatternsPHP#254]
https://github.com/domnikl/DesignPatternsPHP/blob/master/Creational/Multiton/Multiton.php
`final class Multiton { ... }` missed or omitted? In Singleton it exists? what difference?

**Comment by domnikl** [comment]
There is no difference, you could add final to Multiton if you want and send me a PR :)

**Comment by AngeIII** [comment]
I think the final is not needed because we probably can use it via extends, but if final will be used it will cause fatal error:
` Class ChildClass may not inherit from final class (Multiton)`

**Comment by ihor** [comment]
The current implementation won't work with inheritance since it uses ```self```.

**Comment by AngeIII** [comment]
@ihor yep you're right, better to use Trait there..

**Comment by domnikl** [comment]
I added `final` to Multiton. You shouldn't extend from a Multiton and you shouldn't use Multiton at all. It introduces global state in your code and is a therefor an anti pattern.
