### ISSUE TITLE
How is the UML samples draw by yFile?

### ISSUE THREAD

**Issue by phoenixg** [domnikl/DesignPatternsPHP#257]

**Comment by domnikl** [comment]
What do you mean? I use PhpStorm to generate the UML diagrams if thats what your question is.

**Comment by phoenixg** [comment]
@domnikl So PhpStorm can generate PHP to UML diagrams, could you tell me how to do that please?

**Comment by phoenixg** [comment]
Find this: https://confluence.jetbrains.com/display/PhpStorm/Working+with+UML+class+diagrams

Thank you!

**Comment by malukenho** [comment]
@phoenixg https://confluence.jetbrains.com/display/PhpStorm/Working+with+UML+class+diagrams

**Comment by geekcom** [comment]
Great tip, thx @phoenixg
