### ISSUE TITLE
Composite pattern: Suggestion to add a note about nested forms in test

### ISSUE THREAD

**Issue by mcampbell508** [domnikl/DesignPatternsPHP#264]
I have noticed the following in `Structural/Composite/Tests/CompositeTest.php`.

Even though the following test demonstrates the example for this pattern well, technically you cannot nest html forms, that I know of. https://www.w3.org/TR/html5/forms.html#the-form-element

```
public function testRender()
    {
        $form = new Composite\Form();
        $form->addElement(new Composite\TextElement('Email:'));
        $form->addElement(new Composite\InputElement());
        $embed = new Composite\Form();
        $embed->addElement(new Composite\TextElement('Password:'));
        $embed->addElement(new Composite\InputElement());
        $form->addElement($embed);
        $this->assertEquals(
            '<form>Email:<input type="text" /><form>Password:<input type="text" /></form></form>',
            $form->render()
        );
    }
```

Maybe there could be some notes added as part of the doc block for the test, or an inline comment - something along the lines of the following?

> This is just an example, in a real world scenario you are not able to nest HTML forms.

I can create a PR, if this would be welcomed...

Anyways - this repository is awesome, thanks!!

**Comment by domnikl** [comment]
@mcampbell508 looks good, please go on and create a PR I would be happy to merge it in!
