### ISSUE TITLE
Suggestion: add searchable topics to project

### ISSUE THREAD

**Issue by mcampbell508** [domnikl/DesignPatternsPHP#265]
Now that GitHub has introduced its [topic feature](https://help.github.com/articles/about-topics/) to make projects more searchable; I think it would really help others like me who didn't know about this fantastic project, to add (at least) the following topics:

- design patterns
- design-pattern
- oop
- modern-php
- code-examples
- phpunit

These are just suggestions for you to take on board if you'd like...

Anyways thanks!

**Comment by domnikl** [comment]
Thanks for pointing this out! I must have missed it. I added most of your suggestions but "design patterns" is not possible, because it contains a space. I added designpatternsphp instead.
Thank you!
