### ISSUE TITLE
issue on testing AbstractFactory

### ISSUE THREAD

**Issue by mehranhadidi** [domnikl/DesignPatternsPHP#279]
i did the same AbstractFactory. actually i rewrite it. the only thing is difference between my code & the samples is about: HtmlText and JsonText constructor classes. here is my HtmlText

```php
class HtmlText extends Text
{
    public function __construct($text)
    {
        return 'HTML: ' . $text . '\n\t';
    }
}
```

and this is my test

```php
$factory = new HtmlFactory();
$text = $factory->createText('Hello World'); // will generate HTML text
var_dump($text);
```

when i run the code the string is null but everything is ok. can you help me please

**Comment by Hyunk3l** [comment]
When you create a new instance of a class, constructor is called but cannot have a return value.
```
class HtmlText extends Text
{
    private $text;

    public function __construct($text)
    {
        $this->text = $text;
    }
}
```

but class Text is already doing it.

**Comment by mehranhadidi** [comment]
@Hyunk3l thanks for reply. i change my HtmlText class to the way you showed me still getting but its not going to work. can u please check the my code? i really cant get it to work.

https://github.com/mehranhadidi/php-design-patterns/

**Comment by Hyunk3l** [comment]
hello @mehranhadidi 
post here the error please
