### ISSUE TITLE
Provided only partial implementation of Strategy pattern

### ISSUE THREAD

**Issue by mikkitiger** [domnikl/DesignPatternsPHP#282]
Compare provided code with this:
[https://sourcemaking.com/design_patterns/strategy/php](https://sourcemaking.com/design_patterns/strategy/php)

Main reason of strategy pattern is to make a decision  - choose appropriate processing method based on some informations. This is made by StrategyContext.
In your implementation this functionality is not existing.

**Comment by domnikl** [comment]
You are free to change the code and send me a PR, I would be happy to merge it! :)

**Comment by EduardoGR** [comment]
i am going to do it! :)
