### ISSUE TITLE
Factory Method and Abstract Factory patterns are the same

### ISSUE THREAD

**Issue by dergus** [domnikl/DesignPatternsPHP#292]
It seems to me that they're the same and there is no actual difference between them.

**Comment by a-komarev** [comment]
Couple of words about factories: https://medium.com/@mlbors/a-word-about-factories-25b777e9d6c7

**Comment by sergej-kurakin** [comment]
:+1:

**Comment by domnikl** [comment]
I reworked both of the patterns and I think the difference between them is now more obvious than before. Have a look if you want.
