### ISSUE TITLE
PL translation is missing on readthedocs

### ISSUE THREAD

**Issue by piotrgradzinski** [domnikl/DesignPatternsPHP#296]
Hi @domnikl !
Thanks for the PR merge! I've checked the http://designpatternsphp.readthedocs.io/en/latest/ docs and as far I as can see the polish translation is missing from the list. There are en, de x2, es x2, pt, ru, zh. 

I tried to build the docs once again but without success. 

Can you please add polish translation also there? 

Many thanks!

**Comment by piotrgradzinski** [comment]
@domnikl - I would be great if you could take a look on that since lack of the polish in readthedocks is a huge disadvantage. Having this is crutial for readers since they wan't clone the repo and browser .md's. 

Thanks!

**Comment by domnikl** [comment]
@piotrgradzinski it was missing, because each translation needs to be in a new project and creating a new is a lot of work to do. I created it and linked it, now its available in polish, too.
