### ISSUE TITLE
FlyweightFactory with static fields and methods?

### ISSUE THREAD

**Issue by liweiyi88** [domnikl/DesignPatternsPHP#298]
Would this [line](https://github.com/domnikl/DesignPatternsPHP/blob/master/Structural/Flyweight/FlyweightFactory.php#L14) be 
```
private static $pool = [] 
```
and make the `get` method to `static get`?

**Comment by domnikl** [comment]
@liweiyi88 yes you could change the methods and `$pool` to static. But remember that static methods are not that easy and comfortably when writing unit tests.
