### ISSUE TITLE
Filter Pattern

### ISSUE THREAD

**Issue by AJenbo** [domnikl/DesignPatternsPHP#299]
Filter pattern is very helpful in reducing excessive parameters and avoid a host of filter functions. So might be nice to add it to the page.

An example in Java:
http://www.tutorialspoint.com/design_pattern/filter_pattern.htm

**Comment by domnikl** [comment]
Hi @AJenbo and thanks for the idea. But I don't think this is a necessary pattern that everyone should know about. There is hardly any more information found on Google or Wikipedia about it and the pattern is not common to anyone I spoke with. 

@piotrgradzinski what's your take on this?

**Comment by piotrgradzinski** [comment]
Dear @AJenbo!
I have to agree with @domnikl in terms of the popularity of this pattern. For sure this one is not as widely used as others described within this repository. Also, please take into consideration that patterns described in 'others' section are not canonical  (in terms of Go4) yet heavily used across different frameworks and libraries. 

This pattern itself is really interesting but in my feeling it may not be commonly used in daily tasks.

Also _filtering pattern_ or more extended _Pipeline and Filter_ I've found are often related or compared with _Chain of Responsibilities_. Sure, it's not the same but have things in common. 

Some links for descriptions I've found for further reference:
https://docs.microsoft.com/en-us/azure/architecture/patterns/pipes-and-filters
https://github.com/thephpleague/pipeline

**Comment by piotrgradzinski** [comment]
I will close the issue. Open another if needed.
