### ISSUE TITLE
Your design patterns does not know about SOLID Principles!

### ISSUE THREAD

**Issue by dmitrirussu** [domnikl/DesignPatternsPHP#304]
Could you upgrade your Design Patterns examples based on SOLID principles?
now must of them don't know about SOLID :), will be very interesting to see them based on this SOLID Principles. 

Thanks

**Comment by domnikl** [comment]
@dmitrirussu If you want them to be based on SOLID principles you could work on it and I'd be happy to merge a PR. Otherwise I am going to close this.

**Comment by dmitrirussu** [comment]
ok, :)

**Comment by dmitrirussu** [comment]
@domnikl Hi, I have asqed mentor of SOLID principle what we should do if we suspect pattern of SOLID principles violation . Answer is next. All 24 patterns are based on SOLID principles, even if we suspect violation of SOLID principles we have to implement them if we see for us a solution. So nothing to change in your Design Patterns stuff :). SOLID principles are to Abstract, each of us can understood and implement how he believes, it mean ideal system does not exist and SOLID principle is not applicable anywhere.
