### ISSUE TITLE
static factory seemed off

### ISSUE THREAD

**Issue by eimihar** [domnikl/DesignPatternsPHP#307]
http://designpatternsphp.readthedocs.io/en/latest/Creational/StaticFactory/README.html

most of static factory implementation I see does not seem to require another class, as the factory method itself is implemented statically on the same type. examples are like :

php datetime Carbon library, like ```Carbon::now()```
http://carbon.nesbot.com/docs/

guzzlehttp ```ServerRequest::fromGlobals()```
https://github.com/guzzle/psr7/blob/master/src/ServerRequest.php

and even php ```DateTime::createFromFormat()``` itself

another examples in c# (static methods), referring to static factory methods in creating Vector3
https://docs.unity3d.com/ScriptReference/Vector3.html

or please correct me if my understanding is wrong. I think it's one of the most used pattern out there. or is this documentation isn't meant to be for static factory method?

**Comment by piotrgradzinski** [comment]
I think that both approaches are OK. 
I mentioned examples you have one static factory per class which is returning objects for class that is attached to. And this is OK. The example that is present in this repository assumes that you have multiple classes sharing same interface and you want to create those objects from one static factory. You could split this and setup static factory separately for FormatNumber and FormatString but in this particular example it would be a code duplication. 

It makes any sense for you?

**Comment by eimihar** [comment]
Okay, I think I can say that `static factory` and `static factory method` is totally two different things. 

As in my opinion, the pattern introduced here (`static factory`) is so unheard of, and going to be confused with the famous `static factory method` pattern..

**Comment by piotrgradzinski** [comment]
@eimihar - true. 
On the other hand there is [Factory Method](http://designpatternsphp.readthedocs.io/en/latest/Creational/FactoryMethod/README.html) described. Not static of course but gives a general idea. 

Please feel more thank welcome to contribute Static Factory Method pattern to the repo :)
