### ISSUE TITLE
Translation issues.

### ISSUE THREAD

**Issue by k-gun** [domnikl/DesignPatternsPHP#313]
Hi. There are some translation issues (suppose related with RtD) that I would like share.

Some of these translations are not appearing (parenthesized parts):
```
#: ../../Creational/Prototype/README.rst:1
msgid "Prototype"
msgstr "Prototype (Prototip)"
```
---

There are no "THIS IS CONSIDERED TO BE AN ANTI-PATTERN!" and "Service Locator is considered for some ..." paragraphs to translate:
http://designpatternsphp.readthedocs.io/tr/latest/More/ServiceLocator/README.html#service-locator
https://github.com/domnikl/DesignPatternsPHP/blob/master/locale/tr/LC_MESSAGES/More/ServiceLocator/README.po#L14

---

These are not processed as translated:

http://designpatternsphp.readthedocs.io/tr/latest/Creational/FactoryMethod/README.html#purpose
https://github.com/domnikl/DesignPatternsPHP/blob/master/locale/tr/LC_MESSAGES/Creational/FactoryMethod/README.po#L22
https://github.com/domnikl/DesignPatternsPHP/blob/master/locale/tr/LC_MESSAGES/Creational/FactoryMethod/README.po#L31

http://designpatternsphp.readthedocs.io/tr/latest/Creational/SimpleFactory/README.html#purpose
https://github.com/domnikl/DesignPatternsPHP/blob/master/locale/tr/LC_MESSAGES/Creational/SimpleFactory/README.po#L26

http://designpatternsphp.readthedocs.io/tr/latest/Structural/DependencyInjection/README.html#usage
https://github.com/domnikl/DesignPatternsPHP/blob/master/locale/tr/LC_MESSAGES/Structural/DependencyInjection/README.po#L34

http://designpatternsphp.readthedocs.io/tr/latest/Behavioral/ChainOfResponsibilities/README.html#examples
https://github.com/domnikl/DesignPatternsPHP/blob/master/locale/tr/LC_MESSAGES/Behavioral/ChainOfResponsibilities/README.po#L35
https://github.com/domnikl/DesignPatternsPHP/blob/master/locale/tr/LC_MESSAGES/Behavioral/ChainOfResponsibilities/README.po#L43
https://github.com/domnikl/DesignPatternsPHP/blob/master/locale/tr/LC_MESSAGES/Behavioral/ChainOfResponsibilities/README.po#L47

http://designpatternsphp.readthedocs.io/tr/latest/Behavioral/Command/README.html#examples
https://github.com/domnikl/DesignPatternsPHP/blob/master/locale/tr/LC_MESSAGES/Behavioral/Command/README.po#L64
https://github.com/domnikl/DesignPatternsPHP/blob/master/locale/tr/LC_MESSAGES/Behavioral/Command/README.po#L72

http://designpatternsphp.readthedocs.io/tr/latest/Behavioral/Iterator/README.html#examples
https://github.com/domnikl/DesignPatternsPHP/blob/master/locale/tr/LC_MESSAGES/Behavioral/Iterator/README.po#L31
http://designpatternsphp.readthedocs.io/tr/latest/Behavioral/Iterator/README.html#note
https://github.com/domnikl/DesignPatternsPHP/blob/master/locale/tr/LC_MESSAGES/Behavioral/Iterator/README.po#L44

http://designpatternsphp.readthedocs.io/tr/latest/Behavioral/Memento/README.html#examples
https://github.com/domnikl/DesignPatternsPHP/blob/master/locale/tr/LC_MESSAGES/Behavioral/Memento/README.po#L96
https://github.com/domnikl/DesignPatternsPHP/blob/master/locale/tr/LC_MESSAGES/Behavioral/Memento/README.po#L100
https://github.com/domnikl/DesignPatternsPHP/blob/master/locale/tr/LC_MESSAGES/Behavioral/Memento/README.po#L104

http://designpatternsphp.readthedocs.io/tr/latest/Behavioral/NullObject/README.html#purpose
https://github.com/domnikl/DesignPatternsPHP/blob/master/locale/tr/LC_MESSAGES/Behavioral/NullObject/README.po#L32
https://github.com/domnikl/DesignPatternsPHP/blob/master/locale/tr/LC_MESSAGES/Behavioral/NullObject/README.po#L37
https://github.com/domnikl/DesignPatternsPHP/blob/master/locale/tr/LC_MESSAGES/Behavioral/NullObject/README.po#L40
http://designpatternsphp.readthedocs.io/tr/latest/Behavioral/NullObject/README.html#examples
https://github.com/domnikl/DesignPatternsPHP/blob/master/locale/tr/LC_MESSAGES/Behavioral/NullObject/README.po#L62
https://github.com/domnikl/DesignPatternsPHP/blob/master/locale/tr/LC_MESSAGES/Behavioral/NullObject/README.po#L66
https://github.com/domnikl/DesignPatternsPHP/blob/master/locale/tr/LC_MESSAGES/Behavioral/NullObject/README.po#L70
https://github.com/domnikl/DesignPatternsPHP/blob/master/locale/tr/LC_MESSAGES/Behavioral/NullObject/README.po#L75

http://designpatternsphp.readthedocs.io/tr/latest/Behavioral/Observer/README.html#examples
https://github.com/domnikl/DesignPatternsPHP/blob/master/locale/tr/LC_MESSAGES/Behavioral/Observer/README.po#L38

http://designpatternsphp.readthedocs.io/tr/latest/Behavioral/Strategy/README.html#terminology
https://github.com/domnikl/DesignPatternsPHP/blob/master/locale/tr/LC_MESSAGES/Behavioral/Strategy/README.po#L18
http://designpatternsphp.readthedocs.io/tr/latest/Behavioral/Strategy/README.html#examples
https://github.com/domnikl/DesignPatternsPHP/blob/master/locale/tr/LC_MESSAGES/Behavioral/Strategy/README.po#L48
https://github.com/domnikl/DesignPatternsPHP/blob/master/locale/tr/LC_MESSAGES/Behavioral/Strategy/README.po#L53

http://designpatternsphp.readthedocs.io/tr/latest/Behavioral/TemplateMethod/README.html#purpose
https://github.com/domnikl/DesignPatternsPHP/blob/master/locale/tr/LC_MESSAGES/Behavioral/TemplateMethod/README.po#L37
https://github.com/domnikl/DesignPatternsPHP/blob/master/locale/tr/LC_MESSAGES/Behavioral/TemplateMethod/README.po#L47

**Comment by domnikl** [comment]
Hi @k-gun, I am not able to fix these issues. The original strings have changed, so the translations do no longer match, but I can not translate them. If you really want to help, you could fix it and send a PR.
