### ISSUE TITLE
docker-compose up error

### ISSUE THREAD

**Issue by Isengo1989** [domnikl/DesignPatternsPHP#315]
Attaching to designpatternsphp_php_1
php_1  | Installing composer...
php_1  | Installer corrupt
php_1  | Could not open input file: composer-setup.php
php_1  | 
php_1  | Warning: unlink(composer-setup.php): No such file or directory in Command line code on line 1
php_1  | Downloading dependencies using composer...
php_1  | Could not open input file: composer.phar
php_1  | Running tests...
php_1  | /opt/php/docker/test_runner.sh: line 15: ./vendor/bin/phpunit: No such file or directory
php_1  | Tests failed :(

**Comment by domnikl** [comment]
@Isengo1989 is now fixed in current master, the problem here has been a checksum problem.
