### ISSUE TITLE
AbstractFactory example not good

### ISSUE THREAD

**Issue by akomm** [domnikl/DesignPatternsPHP#332]
The example does not show, why AbstractFactory is useful.

- AbstractFactory does not implement anything, it is simply an interface.
- AbstractFactory is never used directly, so those two HtmlFactory and JsonFactory classes could be two independend classes with same or different API (no abstract contract usage in the example!) and you will not see a difference as far as the example goes.

The tutorial even says: 
```
 The client of the abstract factory
```

But the example does not contain any abstract factory usage, so there is no abstract factory `client`.

**Comment by domnikl** [comment]
Hi @akomm, I do accept PRs on this repo, so if you have a better example, go for it!
