### ISSUE TITLE
Update Copyright Year on https://designpatternsphp.readthedocs.io

### ISSUE THREAD

**Issue by ryantfowler** [domnikl/DesignPatternsPHP#339]
Hi,

The Copyright year on https://designpatternsphp.readthedocs.io reflects 2015, which gives the impression that this resource is out of date. I only found that there is recent activity when visiting this repository.

I didn't see where I could accomplish this via github.com or I would have opened some PR(s). If I am missing something, please let me know and I'll create some PR(s).

Thank you for this resource.

**Comment by domnikl** [comment]
fixed in #340. That is configured in `conf.py` for the Sphinx build for RTD.
