### ISSUE TITLE
Docker is not built

### ISSUE THREAD

**Issue by Daisuke-sama** [domnikl/DesignPatternsPHP#343]
Hi, 

ERROR: Service 'php' failed to build: The command '/bin/sh -c apt-get update     && apt-get install -y zlib1g-dev wget git-core python-pip     && docker-php-ext-install zip     && pip install Sphinx' returned a non-zero code: 100

I am constantly receiving this error.
What do you think it could be?

**Comment by domnikl** [comment]
Hi @Daisuke-sama, could you please post the full output of `docker-compose up --build`?

**Comment by domnikl** [comment]
Ok, found it myself. Please try again with current master.
