### ISSUE TITLE
file DesignPatternsPHP/Creational/AbstractFactory/CsvParser.php 

### ISSUE THREAD

**Issue by dujuwen** [domnikl/DesignPatternsPHP#345]
line 22:
$headerWasParsed = false;

line 26:
if (!$headerWasParsed && $this->skipHeaderLine === self::OPTION_CONTAINS_HEADER) {

Is variable $headerWasParsed redundant?

**Comment by domnikl** [comment]
Was fixed in 643b0539d1690eb0320b3496b1135ab0be100829
