### ISSUE TITLE
[Suggestions] Is there any possibility to add MIXIN in this docs?

### ISSUE THREAD

**Issue by shanezhiu** [domnikl/DesignPatternsPHP#346]
Is there any possibility to add MIXIN in this docs?

**Comment by domnikl** [comment]
What do you mean by that? I only know mixins from languages like Ruby where they are a language construct. PHP does have traits instead.

**Comment by shanezhiu** [comment]
Actually, it's a method that like traits achieved in Yii2 framework [behaviors](https://www.yiiframework.com/doc/guide/2.0/en/concept-behaviors)

**Comment by domnikl** [comment]
Seems to me that those behaviors are very specific to Yii2 and not a general design pattern to be applicable to general PHP code. So I won't add it.

**Comment by shanezhiu** [comment]
Fine.
