### ISSUE TITLE
[Discussion] Should Repository be marked as anti-pattern?

### ISSUE THREAD

**Issue by roma-glushko** [domnikl/DesignPatternsPHP#347]
Hi there,
Should repository pattern be marked as anti-pattern?

It seems it behave like a helper or a multi-task manager that is doing too much and responsible for both reading and writing information. Depends on system/platform, such repository classes can require a lot of dependencies because of breaking SRP and it becomes a big deal to instantiate them which is possible performance bottleneck.

As an example of better way of dealing with data, I can suggest adding CQRS pattern and referrer it from repository one. 

What's you point of view?
Thanks!

**Comment by domnikl** [comment]
Hi @roma-glushko,
I think that the Repository pattern is no anti-pattern. Instead it is a very important pattern in Domain Driven Design to encapsulate persistence and provide a simple facade to it. Clients of the repository don't care how those requested aggregates are persisted.

It also works very well with CQRS architectures where it supports the Command side of the application in getting and updating domain objects.

I don't think there is a design pattern that violates the Single Responsiblity Principle per se. It all depends on concrete implementation. That being said the SRP is also the single most misunderstood principle of the 5 SOLID principles. 

> A class should have only one reason to change.

It's about reasons to change. Most of the time the reading and writing of data in the repository happens from the same table(s) stored in a database so there is only one reason to change it: if the database structure changes. And that will cause reading AND writing to change.

For me, the repository is only the facade to persistence. Most of my implementations use a Unit Of Work to persist changes and a Loader of some sort to actually load data from a database. That's 2 dependencies, so 3 classes in total which is not a performance bottleneck.

Adding CQRS is a good idea though 👍
