### ISSUE TITLE
May the abstract factory example be confusing?

### ISSUE THREAD

**Issue by koraykupe** [domnikl/DesignPatternsPHP#350]
Hi,

As far as I know, the abstract factory creates the object from a different interface for each product family, but the examples look like the opposite way.

For the abstract method, I think there are a few different ways to implement it.

What do you think?

**Comment by abdulrahman19** [comment]
Yes the current Abstract factory example is so confusing. Also the factory class itself doesn't have an interface to ensure that every object collection (grouped) with the same conventions.

![abfaccldia](https://user-images.githubusercontent.com/22733622/50881536-98e61000-13ea-11e9-8227-19daecb7ac70.jpg)

I hope to review the current example.

**Comment by lukeduda** [comment]
Yes, example is horrible. Based on it wanted to find difference between Factory Method and Abstract factory and it make that so confusing. 
Funny thing is that polish trnanslation has some older example which in my opinion is better
https://designpatternsphp.readthedocs.io/pl/latest/Creational/AbstractFactory/README.html

![Old example for Abstract Factory](https://designpatternsphp.readthedocs.io/pl/latest/_images/uml12.png)

**Comment by widoz** [comment]
I would also specify better what "Abstract" in this context means, the example image of @lukeduda is showing a Factory Method not an Abstract Factory, see differences between PL and EN https://designpatternsphp.readthedocs.io/en/latest/Creational/AbstractFactory/README.html the "abstract" in AbstractFactory seems is not intended to be Abstract _class_ or _interface_, I'm surely wrong but sounds more _hide the creation of object_ but the class is a concrete class that expose multiple methods to create different objects even though they share the same interface.

**Comment by domnikl** [comment]
Yes you are right, the example is confusing and not showing an Abstract Factory but a Factory Method instead. I will rewrite it in the next days and get back here with a PR for the new example.

**Comment by domnikl** [comment]
I rewrote the example in #366. Please review the PR and leave any comments you have there. Thanks!

**Comment by domnikl** [comment]
#366 is now merged and I hope everyone likes the new example :)
