### ISSUE TITLE
Out-dated Specifications pattern

### ISSUE THREAD

**Issue by BentCoder** [domnikl/DesignPatternsPHP#352]
Hi,

The [Specifications](https://github.com/domnikl/DesignPatternsPHP/tree/master/Behavioral/Specification) pattern seems to be out-dated. The diagram, Readme and the actual class files don't match.

Regards

**Comment by domnikl** [comment]
fixed in 23e520aee9e5919cb7f5279e7a01c0487d08ec94, thanks for reporting!
