### ISSUE TITLE
Generate uml diagram by phpstorm is not good idea.

### ISSUE THREAD

**Issue by ko22009** [domnikl/DesignPatternsPHP#369]
For example mediator have the next demonstration, but in the phpstorm is not the same. It create wrong picture. It's problem of php. Bcz only php 7.4 and above support Typed Class Properties. reverse engineering php with phpdoc will be work correctly with earlier versions of php.
![image](https://user-images.githubusercontent.com/11016041/65364650-b54e7380-dc2c-11e9-929d-96efa0b738ea.png)
![Alt text](https://raw.githubusercontent.com/domnikl/DesignPatternsPHP/master/Behavioral/Mediator/uml/uml.png?raw=true "Optional Title")

**Comment by domnikl** [comment]
Hi @ko22009, I totally see your point. Care to provide a PR for an alternative?

**Comment by ko22009** [comment]
@domnikl Maybe after reliaze php 7.4 we can see it. Waiting is not long, November 28

**Comment by vladyslavstartsev** [comment]
@ko22009 @domnikl ping! Any news?

**Comment by ko22009** [comment]
@vladyslavstartsev 
There is no decision for now.
Maybe automatic creating diagram is not good decision.

**Comment by domnikl** [comment]
@vladyslavstartsev as @ko22009 already said: there is no decision right now. I've reviewed some tools to automatically generate diagrams but they all do not look as good as the ones generated by PhpStorm. So for now, I will go with that.

**Comment by domnikl** [comment]
As there isn't any progress here and I do not see an eligible alternative by now, I am closing this.
