### ISSUE TITLE
Aspect Oriented Programming (AOP)

### ISSUE THREAD

**Issue by Sarke** [domnikl/DesignPatternsPHP#370]
I don't have any experience with it, but I've heard about it being used in PHP.  It could be added if anyone is interested.

http://aop-php.github.io/

https://github.com/goaop/framework

**Comment by oLDu67** [comment]
Also you can use decorator pattern for aop.

**Comment by domnikl** [comment]
Hi @Sarke and thanks for your proposal! I don't want to add it though. The reason being that AOP is a whole paradigm not just a pattern and you need to build complex frameworks in order to use it and that would be too much to do here and I also don't want any dependency on a framework here.
