### ISSUE TITLE
Singleton and static keyword

### ISSUE THREAD

**Issue by permiakov** [domnikl/DesignPatternsPHP#371]
Hi guys, i was wandering what the purpose of using **static**, if your class marked as **Final**?
```
final class Singleton
{
........
/**
     * gets the instance via lazy initialization (created on first usage)
     */
    public static function getInstance(): Singleton
    {
        if (static::$instance === null) {
            static::$instance = new static();
        }

        return static::$instance;
    }
```

**Comment by jirkavrba** [comment]
`Final` has nothing to do with the `static` keyword.
`Static` keyword means that the property or value is bound to class not instance. This means that when you have a static attribute, it is shared between all instances of that class. If you have a static method it means you have to call it on the class as a whole not it's instance. 
```php
class StaticClass 
{
    private static $someAttribute;

    public function setValue(string $newValue)
    {
         static::$someAttribute = $newValue;
    }
    
    public function getValue(): string
    {
           return static::$someAttribute;
    }
}

class NonStaticClass
{
    private $someAttirbute;
    
    public function setValue(string $newValue)
    {
         $this->someAttribute = $newValue;
    }
    
    public function getValue(): string
    {
           return $this->someAttribute;
    }
}


// Static instances shares the $someAttribute value as it belongs to the class not instance
$instance1 = new StaticClass();
$instance2 = new StaticClass();

$instance1->setValue("first");
$instance2->setValue("second");

echo $instance1->getValue(); // "second"
echo $instance2->getValue(); // "second"

// However the non static class instances each has its own value

$instance1 = new NonStaticClass();
$instance2 = new NonStaticClass();

$instance1->setValue("first");
$instance2->setValue("second");

echo $instance1->getValue(); // "first"
echo $instance2->getValue(); // "second"
```

The `final` keyword indicates, that the class cannot be extended. That means that no class can be children of the class marked as final. You can also define class methods as final which means that if you inherit the parent class you cannot overload that method.

I hope it is somehow clear and not too much confusing.

**Comment by permiakov** [comment]
Okay, then what is the difference between 2 calls
static::$var
and
self::$var
?

**Comment by jirkavrba** [comment]
There is a difference that the `static` and `self` references class where it is defined,
But if you inherit a class then it gets different. Consider having two classes: class `Parent` and class `Child` which extends `Parent`. If you use both keywords in `Parent` self will always be pointing to `Parent`. But the inherited class `Children` will override `static` which is then pointing to `Children` class.

In other words. If you access property with `self` it will be always pointing to the class in which you reference it, while the `static` will be pointing to class in which you use it. That is very handy for. eg calling methods in `Parent` that you don't want to be overridden.

For further reading I would suggest this StackOverflow thread https://stackoverflow.com/questions/5197300/new-self-vs-new-static

Hope it helps

**Comment by permiakov** [comment]
Looks like you almost understood the main question

**Comment by domnikl** [comment]
Hi @permiakov, when a class is final, it makes no difference if you use `static` or `self`. So there is no real need for it here, just a personal preference in this case.
