### ISSUE TITLE
Dockerfile should use multi-stage build

### ISSUE THREAD

**Issue by domnikl** [domnikl/DesignPatternsPHP#376]
Docs using Sphinx should be build in a Python container and then copied over to a fresh nginx container to serve the docs, no PHP needed here.

**Comment by Netvilox** [comment]
Please am new here but I have a website I want to create plugin for how do I start. I have little knowledge about php, html, and css

[Netvilox.com](Netvilox )

**Comment by domnikl** [comment]
done in be66dcc
