### ISSUE TITLE
Patterns order

### ISSUE THREAD

**Issue by ajest** [domnikl/DesignPatternsPHP#392]
I just want to suggest to order the patterns by complexity or logic relation, for example StaticFactory maybe is the first step, then SimpleFactory, and then AbstractFactory. Another idea is to write below "related patterns" to make easiear to understand them.
Thanks!

**Comment by 20jam** [comment]
Thats a great idea, I wonder if a page title quickstart, or something would make this easy to implement this.

**Comment by domnikl** [comment]
There would be 2 places where ordering could be applied: the README and the front page of the readthedocs page. But how do you measure complexity here? Logic relation applies only to very few patterns here.

**Comment by ajest** [comment]
> There would be 2 places where ordering could be applied: the README and the front page of the readthedocs page. But how do you measure complexity here? Logic relation applies only to very few patterns here.

Your right, it seems like it only applies to the creational patterns section. Thanks for replying!
