### ISSUE TITLE
list existing translations in the README

### ISSUE THREAD

**Issue by domnikl** [domnikl/DesignPatternsPHP#398]
To better show which translations exist, there should be a list in the README for that.

**Comment by NeonDevil** [comment]
#399

**Comment by domnikl** [comment]
Thanks for the PR @NeonDevil! I know the issue didn't specify it, but we should put links to read the docs.org in here for all the languages and also for the default (english). Care to change it?

**Comment by lix-dev** [comment]
Completed in #401 ;)

**Comment by domnikl** [comment]
Done in #401, thank you @NeonDevil and @lix-dev for your effort!
