### ISSUE TITLE
Broken documentation url in readme

### ISSUE THREAD

**Issue by bu4ak** [domnikl/DesignPatternsPHP#403]
![изображение](https://user-images.githubusercontent.com/17143820/95062061-bac61100-06fc-11eb-92fa-88ee2af32f68.png)

___
returns
___
![изображение](https://user-images.githubusercontent.com/17143820/95061758-51460280-06fc-11eb-9041-7b054e3b10a8.png)

**Comment by harsha14581** [comment]
Hi @bu4ak, i have created a PR request for this issue. PR request is https://github.com/domnikl/DesignPatternsPHP/pull/408

**Comment by bu4ak** [comment]
> Hi @bu4ak, i have created a PR request for this issue. PR request is https://github.com/domnikl/DesignPatternsPHP/pull/408
> 
> 

![image](https://user-images.githubusercontent.com/17143820/95676890-de3c0080-0bc1-11eb-8029-713b381d5966.jpeg)
