### ISSUE TITLE
Bulgarian Translation

### ISSUE THREAD

**Issue by korzol** [domnikl/DesignPatternsPHP#418]
Hello there
Excellent documentation!
I'd like to translate it into Bulgarian. What's the best approach? 
Is it enough to only create *.po files under locale/bg/LC_MESSAGES ?

Thank you!

**Comment by domnikl** [comment]
Hello @korzol, please also add a link in the [README.md](https://github.com/domnikl/DesignPatternsPHP/blob/main/README.md). If you are ready, I will create a new readthedocs project from it and link it to the main project. Thanks!

**Comment by korzol** [comment]
Hello @dominikb, I already started work on translation. Hope to finish it this weekend

**Comment by korzol** [comment]
Hello @domnikl 
Did you have a chance to check out my pull request?

Regards

**Comment by domnikl** [comment]
Hi @korzol, looks great! Thanks for your hard work! Merged it and is now available on RTD.
