### ISSUE TITLE
Hello 。When I run phpunit, this error occurs. How can I solve it? Thank you

### ISSUE THREAD

**Issue by sunmengkai** [domnikl/DesignPatternsPHP#420]
![image](https://user-images.githubusercontent.com/23547499/104166983-9170fb80-5436-11eb-9487-71875f45df01.png)

**Comment by sunmengkai** [comment]
There was 1 error:

1) Error
The data provider specified for DesignPatterns\Creational\AbstractFactory\Tests\AbstractFactoryTest::testCanCreateCsvWriterOnUnix is invalid.
Error: Class 'DesignPatterns\Creational\AbstractFactory\UnixWriterFactory' not found
E:\phpstudy\phpstudy_pro\WWW\index\DesignPatterns\Creational\AbstractFactory\Tests\AbstractFactoryTest.php:17

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.

**Comment by domnikl** [comment]
Hi @sunmengkai,
based on your directory structure, you are not running `phpunit` from the repository root, thus not loading the `phpunit.xml.dist` configuration which contains the bootstrap (composer's autoloader). Please either run it in the correct directory or explicitely load the configuration file.
