### ISSUE TITLE
SimpleFactory or ConcreteFactory ?

### ISSUE THREAD

**Issue by hgraca** [domnikl/DesignPatternsPHP#89]
The SimpleFactory pattern is referred both in the documentation and in the code, as both SimpleFactory and ConcreteFactory.

I would make a pull request but I actually don't know what is the correct name.

**Comment by andrewnester** [comment]
SimpleFactory + 1

**Comment by andrewnester** [comment]
I've just made PR to change ConcreteFactory name to SimpleFactory
